// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  ArenaRing_glb = "ArenaRing.glb",
  BackgroundTerrain_glb = "BackgroundTerrain.glb",
  Balcony_glb = "Balcony.glb",
  Clouds = "Clouds",
  Clouds01_glb = "Clouds01.glb",
  Clouds02_glb = "Clouds02.glb",
  Clouds03_glb = "Clouds03.glb",
  Clouds04_glb = "Clouds04.glb",
  Clouds05_glb = "Clouds05.glb",
  Clouds06_glb = "Clouds06.glb",
  Gravestone01_glb = "Gravestone01.glb",
  Gravestone01_glb_2 = "Gravestone01.glb_2",
  Gravestone01_glb_3 = "Gravestone01.glb_3",
  Gravestone02_glb = "Gravestone02.glb",
  Gravestone02_glb_2 = "Gravestone02.glb_2",
  Gravestone02_glb_3 = "Gravestone02.glb_3",
  Gravestone02_glb_4 = "Gravestone02.glb_4",
  Gravestone02_glb_5 = "Gravestone02.glb_5",
  Gravestone03_glb = "Gravestone03.glb",
  Gravestone03_glb_2 = "Gravestone03.glb_2",
  Gravestone03_glb_3 = "Gravestone03.glb_3",
  Gravestone03_glb_4 = "Gravestone03.glb_4",
  Gravestone04_glb = "Gravestone04.glb",
  Gravestone04_glb_2 = "Gravestone04.glb_2",
  Gravestone05_glb = "Gravestone05.glb",
  Gravestone05_glb_2 = "Gravestone05.glb_2",
  Gravestone05_glb_3 = "Gravestone05.glb_3",
  Gravestone05_glb_4 = "Gravestone05.glb_4",
  Gravestone05_glb_5 = "Gravestone05.glb_5",
  Gravestone05_glb_6 = "Gravestone05.glb_6",
  Gravestone05_glb_7 = "Gravestone05.glb_7",
  Gravestone05_glb_8 = "Gravestone05.glb_8",
  Lava_glb = "Lava.glb",
  LavaLight_glb = "LavaLight.glb",
  Leaderboard_glb = "Leaderboard.glb",
  Moon_glb = "Moon.glb",
  Pillar01_glb = "Pillar01.glb",
  Pillar01_glb_2 = "Pillar01.glb_2",
  Pillar01_glb_3 = "Pillar01.glb_3",
  Pillar01_glb_4 = "Pillar01.glb_4",
  Pillar01_glb_5 = "Pillar01.glb_5",
  Pillar01_glb_6 = "Pillar01.glb_6",
  Pillar01_glb_7 = "Pillar01.glb_7",
  Pillar01_glb_8 = "Pillar01.glb_8",
  Pillar02_glb = "Pillar02.glb",
  Pillar02_glb_2 = "Pillar02.glb_2",
  Pillar02_glb_3 = "Pillar02.glb_3",
  Pillar02_glb_4 = "Pillar02.glb_4",
  Pillar02_glb_5 = "Pillar02.glb_5",
  Pillar02_glb_6 = "Pillar02.glb_6",
  Props = "Props",
  PumkpinDeco_glb = "PumkpinDeco.glb",
  PumkpinDeco_glb_2 = "PumkpinDeco.glb_2",
  PumpkinDummy_glb = "PumpkinDummy.glb",
  PumpkinDummy_glb_2 = "PumpkinDummy.glb_2",
  PumpkinDummy_glb_3 = "PumpkinDummy.glb_3",
  PumpkinDummy_glb_4 = "PumpkinDummy.glb_4",
  PumpkinDummy_glb_5 = "PumpkinDummy.glb_5",
  Railway_glb = "Railway.glb",
  Sky_glb = "Sky.glb",
  StartGame_glb = "StartGame.glb",
  StartGameLights_glb = "StartGameLights.glb",
  Tree01_glb = "Tree01.glb",
  Tree01_glb_2 = "Tree01.glb_2",
  Tree01_glb_3 = "Tree01.glb_3",
  Tree01_glb_4 = "Tree01.glb_4",
  Tree02_glb = "Tree02.glb",
  Tree02_glb_2 = "Tree02.glb_2",
  Tree02_glb_3 = "Tree02.glb_3",
  Tree02_glb_4 = "Tree02.glb_4",
  Tree02_glb_5 = "Tree02.glb_5",
  Vampire_glb = "Vampire.glb",
} 
